############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "About"
pageRef = "/about"
weight = 2


[[main]]
name = "Products"
pageRef = "/products"
weight = 4


[[main]]
name = "Projects"
pageRef = "/projects"
weight = 5


[[main]]
name = "News"
pageRef = "/news"
weight = 6

[[main]]
name = "Contact"
pageRef = "/contact"
weight = 7




# footer menu
[[footer]]
name = "About"
pageRef = "/about"
weight = 1


[[footer]]
name = "Privacy Policy"
pageRef = "/privacy-policy"
weight = 2
